<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.6</version>
    <relativePath />
  </parent>
  <groupId>githubScoringServiceApi</groupId>
  <artifactId>githubScoringServiceApi</artifactId>
	<version>4.0.12</version>
	<name>GithubScoringServiceApi</name>
	<description>API for the Scoring-Service</description>
  <url>https://github.com/patrickweingartz/githubScoringServiceApi</url>
  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/licenses/MIT</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>patrickweingartz</id>
      <name>Knute Pansen</name>
      <email>deine@email.de</email>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:https://github.com/patrickweingartz/githubScoringServiceApi.git</connection>
    <developerConnection>scm:git:https://github.com/patrickweingartz/githubScoringServiceApi.git</developerConnection>
    <url>https://github.com/patrickweingartz/githubScoringServiceApi</url>
    <tag>HEAD</tag>
  </scm>
	<properties>
		<java.version>21</java.version>
    <generated-api.source-folder>${project.build.directory}/generated-sources/openapi/src/main/java</generated-api.source-folder>
    <generated-api.target-folder>${project.basedir}/src/generated/main/java</generated-api.target-folder>
	</properties>
	<dependencies>
		<!-- -Springboot related dependencies -->
    <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations</artifactId>
      <version>2.2.38</version>
    </dependency>
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
      <version>0.2.4</version>
    </dependency>
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
      <version>3.0.2</version>
    </dependency>
	</dependencies>

	<build>
		<plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>6.6.0</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/GithubScoringApi.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <apiPackage>githubScoringService.api</apiPackage>
              <modelPackage>githubScoringService.model</modelPackage>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <configOptions>
                <dateLibrary>java8</dateLibrary>
                <disallowAdditionalPropertiesIfNotPresent>true</disallowAdditionalPropertiesIfNotPresent>
                <interfaceOnly>true</interfaceOnly>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useJakartaEe>true</useJakartaEe>
                <useSpringBoot3>true</useSpringBoot3>
                <generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                <useBeanValidation>false</useBeanValidation>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-release-plugin</artifactId>
            <version>3.1.1</version>
          </plugin>
        </plugins>
   	</build>

	<distributionManagement>
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/patrickweingartz/githubScoringServiceApi</url>
    </repository>
    <snapshotRepository>
      <id>github</id>
      <name>GitHub Packages Snapshots</name>
      <url>https://maven.pkg.github.com/patrickweingartz/githubScoringServiceApi</url>
    </snapshotRepository>
  </distributionManagement>
</project>
