openapi: 3.0.3
info:
  title: Github-Scoring-Service Api
  description: API for the Scoring-Service processing user defined search requests against the github rest API
  version: 1.0.0
paths:
  /getGithubReposSortedByPopularityScore/:
    get:
      tags:
        - githubScoringService
      operationId: getGithubReposSortedByPopularityScore
      parameters:
        - name: repositoryLanguage
          in: path
          required: false
          description: filters the github repository search by the handed in language
          schema:
            type: string
        - name: minCreationDateOfRepository
          in: path
          required: false
          description: filters the github repository search by the handed in creation date
          schema:
            type: string
            example: YYYY-MM-DD
        - name: authorizationToken
          in: header
          required: false
          description: >
            represents the github authorization Token used to identify against the github rest api.
            Without a valid token the github API will only return a limited set of results.
          schema:
            type: string
      summary: returns a popularity sorted list of github repositories filtered by the handed in language and creationDate
      responses:
        '200':
          description: >
            Searchrequest was successfull delivering a popularity-based-sorted List of github repositories.
            When nothing was found an empty list will be returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './GithubScoringApiTypes.yaml#/components/schemas/GithubRepository'