name: Release Maven Package

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 and configure Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          server-id: github
          settings-path: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.PATS_TOKEN }}

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests
